#!/usr/bin/env perl
use v5.18;
use warnings;

local $SIG{__WARN__} = sub {
    my $warn_text = shift;
    return if $warn_text =~ /\A(given|when) is experimental/;
    return if $warn_text =~ /\ANegative repeat count/;
    warn($warn_text);
};

use Mailsheep::App;

binmode STDOUT, ":utf8";

Mailsheep::App->new->run;
